# Generated by Django 3.2 on 2021-05-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='detail',
            new_name='comment',
        ),
    ]
